### ISSUE TITLE
Can you give compiled binary files Qemu?

### ISSUE THREAD

**Issue by AndreyDaniluk** [devos50/qemu#10]
When i try compile Qemu on Windows, i get error:
![image](https://user-images.githubusercontent.com/89187230/209587464-84c6be45-df4f-493c-bd2a-fed226e4d952.png)
I`m so lazy for finding solution, please anyone, give binary files)

**Comment by lumaaaaaa** [comment]
Hey there, I'm having the same error, were you able to find a solution? Thank you!

**Comment by devos50** [comment]
> cc1.exe: all warnings being treated as errors

Judging from this line, it looks like you need a compiler flag to disable the feature that all warnings are treated as errors, but I would not be sure which one that would be though.

**Comment by stagbar** [comment]
ipod touch 1g with ios 1.1
[https://filetransfer.io/data-package/t99XMeo2#link](url)
