### ISSUE TITLE
How to compile it?

### ISSUE THREAD

**Issue by Treaper333** [devos50/qemu#104]
I don't know how to compile it i tried using msys but the configure command does not work how to setup it?

**Comment by spetterman66** [comment]
1.  Open Mingw64
  2.  Install the relevant packages (see RUNNING.md)
  3.  Run "git clone https://github.com/devos50/qemu-ios.git --depth 1"
  4.  "cd qemu-ios"
  5.  "mkdir iosbuild"
  6.  "cd iosbuild"
  7.  Use the configure command (also see RUNNING.md)
  8.  When the configure command is done, type "make"
  9.  When it's done, download the S5L8720 boot ROM, NOR file, and NAND file, then move them in the iosbuild directory
  10. Run the emulator: "qemu-system-arm -M iPod-Touch,bootrom=<path>,nand=<path to NAND dir>,nor=<path to NOR dir> -serial mon:stdio -cpu max -m 2G -d unimp"

________________________________
From: Lol ***@***.***>
Sent: Tuesday, December 26, 2023 10:56 AM
To: devos50/qemu-ios ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [devos50/qemu-ios] How to compile it? (Issue #104)


I don't know how to compile it i tried usin msys but tghe configure command does not work how to setup mingw64?

**Comment by Treaper333** [comment]
![image](https://github.com/devos50/qemu-ios/assets/69011623/6adcca67-fed2-412e-b6fc-4cf25685a2a8)
i got black screeen

**Comment by MrDiagnose** [comment]
did you extract the nand folder? show logs. 
Build Instructions for 
Windows: https://youtu.be/bxg4QlwENsI
Linux/Ubuntu: https://youtu.be/Jbo42OSVfoA
also don't just use make add the -j argument followed by 2,4,6.. depending upon how many cpu cores you have  & how many you can spare, this will boost you compilation speed  I used "make -j4"

**Comment by Treaper333** [comment]
I just needed to add path directly to the nor and bootrom files not the folders now it worked thank you for all your help
