### ISSUE TITLE
QEMU crashes on WSL with malloc(): invalid size (unsorted) Aborted (core dumped)

### ISSUE THREAD

**Issue by MishaTY** [devos50/qemu#12]
Configure command:  ../configure --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-slirp --extra-cflags=-I/usr/local/opt/openssl@3/include --extra-ldflags='-L/usr/local/opt/openssl@3/lib -lcrypto' --disable-werror
[log.txt](https://github.com/devos50/qemu/files/10316296/log.txt)

**Comment by MishaTY** [comment]
Fixed it by disabling PIE (--disable-pie). I can confirm that this works on WSL / Linux
![image](https://user-images.githubusercontent.com/46088515/209869581-66b8c30f-e5d3-44af-a3fe-1f3dcaa7b16b.png)

**Comment by MishaTY** [comment]
Still randomly happens for me

**Comment by io12** [comment]
I think this compile warning has the issue:
```
../hw/arm/ipod_touch_adm.c: In function ‘ipod_touch_adm_write’:
../hw/arm/ipod_touch_adm.c:178:32: warning: array subscript ‘uint32_t {aka unsigned int}[0]’ is partly outside array bounds of ‘unsigned char[1]’ [-Warray-bounds]
  178 |                         bank = *buf;
      |                                ^~~~
../hw/arm/ipod_touch_adm.c:176:31: note: object of size 1 allocated by ‘malloc’
  176 |                         buf = malloc(1);
      |                               ^~~~~~~~~
../hw/arm/ipod_touch_adm.c:115:37: warning: array subscript ‘uint32_t {aka unsigned int}[0]’ is partly outside array bounds of ‘unsigned char[2]’ [-Warray-bounds]
  115 |                         num_pages = *buf;
      |                                     ^~~~
../hw/arm/ipod_touch_adm.c:113:31: note: object of size 2 allocated by ‘malloc’
  113 |                         buf = malloc(2);
      |                               ^~~~~~~~~
../hw/arm/ipod_touch_adm.c:157:40: warning: array subscript ‘uint32_t {aka unsigned int}[0]’ is partly outside array bounds of ‘unsigned char[1]’ [-Warray-bounds]
  157 |                                 bank = *buf;
      |                                        ^~~~
../hw/arm/ipod_touch_adm.c:155:39: note: object of size 1 allocated by ‘malloc’
  155 |                                 buf = malloc(1);
      |                                       ^~~~~~~~~
../hw/arm/ipod_touch_adm.c:120:36: warning: array subscript ‘uint32_t {aka unsigned int}[0]’ is partly outside array bounds of ‘unsigned char[2]’ [-Warray-bounds]
  120 |                             bank = *buf;
      |                                    ^~~~
../hw/arm/ipod_touch_adm.c:113:31: note: object of size 2 allocated by ‘malloc’
  113 |                         buf = malloc(2);
      |                               ^~~~~~~~~
../hw/arm/ipod_touch_adm.c:78:37: warning: array subscript ‘uint32_t {aka unsigned int}[0]’ is partly outside array bounds of ‘unsigned char[2]’ [-Warray-bounds]
   78 |                         num_pages = *buf;
      |                                     ^~~~
../hw/arm/ipod_touch_adm.c:76:31: note: object of size 2 allocated by ‘malloc’
   76 |                         buf = malloc(2);
      |                               ^~~~~~~~~
```

**Comment by lemonjesus** [comment]
I tried to open a [PR that solves this problem](https://github.com/devos50/qemu/pull/15) but it was immediately closed and locked 🤷‍♂️

Anyway, once you apply these changes it should run a little more predictably on Linux. I still get the occasional floating point exceptions, but I get those on macOS too.

**Comment by io12** [comment]
> I tried to open a PR that solves this problem but it was immediately closed and locked

I think this is because the repo is a fork of a QEMU mirror and QEMU wants people to make PRs to their main repo. I think @devos50 has to delete this file for PRs to work.
https://github.com/devos50/qemu/blob/master/.github/lockdown.yml

**Comment by devos50** [comment]
> I think this is because the repo is a fork of a QEMU mirror and QEMU wants people to make PRs to their main repo. I think @devos50 has to delete this file for PRs to work.

Thanks for bringing this to my attention! I just removed the lockdown file 👍

**Comment by MishaTY** [comment]
Will test after school.

**Comment by MishaTY** [comment]
It now works reliably without any issues!
