### ISSUE TITLE
running third-party applications (.ipa)

### ISSUE THREAD

**Issue by thebreaddev** [devos50/qemu#120]
i tried adding .app to /System/Applications/ (for example [this one](https://archive.org/download/legacyiosapparchive/Mirror%20Mirror-v1.0--iOS2.0-%28Clutch-1.4.6%29.ipa)) and then rebuilding nand but app was crashing on startup. is there a way to run non-apple apps since you can't jailbreak this emulator?
maybe its kernel related or execute permissions missing

**Comment by thebreaddev** [comment]
i changed executable permissions to 777 using chmod and rebuilt nand again but its still crashing with

> int AppleMobileFileIntegrity::validateCodeDirectoryHashInDaemon(vnode*, uint8_t*): no registered daemon port
CODESIGNING: vm_fault_enter(0x1000): page 0xe016dcb4 obj 0xc377a460 off 0x0 *** INVALID PAGE ***

in qemu console

**Comment by devos50** [comment]
Hmm that's unexpected. I got that error before when there was an error related to NAND writes/reads.

It complains that there's no registered daemon port. Maybe this could be related to the fact that I'm not running all the launchd daemons so far (for simplicity)? It could be that a critical process is not started yet. I would have to look into that 👍 .

**Comment by thebreaddev** [comment]
update: i succeeded to run 2 simple apps. to allow their code execution i was needed to modify boot-args. in my fork i committed the "amfi_allow_any_signature=1" boot arg. also executable of .app must be signed (i fakesigned it with ldid -S)

**Comment by devos50** [comment]
@thebreaddev great! Feel free to make a PR to change these boot args 👍.

**Comment by thebreaddev** [comment]
i made a pull request. good luck with your project 👍🏻

**Comment by gdandsm64fan123** [comment]
Damn nice job dude!
