### ISSUE TITLE
Implement DFU Mode

### ISSUE THREAD

**Issue by ChaseKnowlden** [devos50/qemu#123]
#122 starts to implement the DFU mode into the emulator.

**Comment by devos50** [comment]
https://github.com/devos50/qemu-ios/tree/dfu manages to boot into DFU mode, with the USB stack initialized but it's not doing anything useful yet 👍

**Comment by LagLifeYT** [comment]
> https://github.com/devos50/qemu-ios/tree/dfu manages to boot into DFU mode, with the USB stack initialized but it's not doing anything useful yet 👍

Once DFU mode works and a restore can be done (which would require NAND write), it should be possible to boot iOS 3 and 4 in the emulator without having to rebuild the NOR and NAND

**Comment by devos50** [comment]
> Once DFU mode works and a restore can be done (which would require NAND write), it should be possible to boot iOS 3 and 4 in the emulator without having to rebuild the NOR and NAND

Yes, it should! Unfortunately, the USB stack is a bit more complicated than I anticipated so it might take a while to get this up and running 👍

**Comment by LagLifeYT** [comment]
> > Once DFU mode works and a restore can be done (which would require NAND write), it should be possible to boot iOS 3 and 4 in the emulator without having to rebuild the NOR and NAND
> 
> Yes, it should! Unfortunately, the USB stack is a bit more complicated than I anticipated so it might take a while to get this up and running 👍

One more thing: The recovery mode image doesn't display correctly (last time I checked this, it was a white screen), and if the GPU cannot render Springboard when the restore is completed, it'll likely appear to freeze on the Apple logo. 

Obviously disabling the GPU in the rootfs will fix it but once the GPU is fixed there should be no problem just distributing the emulator with just a blank NOR (still will need a SysCfg area) and NAND.
