### ISSUE TITLE
iPod emulator keeps freezing

### ISSUE THREAD

**Issue by ChaseKnowlden** [devos50/qemu#131]
The emulator freezes after 10-15 seconds.

OS: macOS

**Comment by spetterman66** [comment]
What macOS version?
What do you see in the terminal when it freezes?
________________________________
From: Chase Knowlden ***@***.***>
Sent: Sunday, January 21, 2024 12:24 AM
To: devos50/qemu-ios ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [devos50/qemu-ios] iPod emulator keeps freezing (Issue #131)


The emulator freezes after 10-15 seconds.

OS: macOS

**Comment by ChaseKnowlden** [comment]
macOS Sonoma
