### ISSUE TITLE
Ipod touch 2 zsh: no such file or directory: path

### ISSUE THREAD

**Issue by angryduck1** [devos50/qemu#135]
zsh: no such file or directory: path
I am writing command ./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=<path to bootrom>,nand=<path to NAND directory>,nor=<path to NOR directory> -serial mon:stdio -cpu max -m 2G -d unimp

**Comment by MrDiagnose** [comment]
you need these files https://github.com/devos50/qemu-ios/releases/tag/n72ap_v1

**Comment by angryduck1** [comment]
Hello! This error occurred on my Intel MacBook - zsh: no such file or directory: path
I installed all the necessary files, went to the directory where these files were and I get this error iPod Touch 2

**Comment by angryduck1** [comment]
> you need these files https://github.com/devos50/qemu-ios/releases/tag/n72ap_v1Hello! This error occurred on my Intel MacBook - zsh: no such file or directory: path
I installed all the necessary files, went to the directory where these files were and I get this error iPod Touch 2

**Comment by MrDiagnose** [comment]
you didn't provide the location of where the files are in your command 

`./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=<paste_boot_rom_location_here>,nand=<paste_nand_location_here>,nor=<paste_nor_location_here> -serial mon:stdio -cpu max -m 2G -d unimp`

you also need to extract the nand

**Comment by angryduck1** [comment]
> ./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=<paste_boot_rom_location_here>,nand=<paste_nand_location_here>,nor=<paste_nor_location_here> -serial mon:stdio -cpu max -m 2G -d unimp

zsh: no such file or directory: ./arm-softmmu/qemu-system-arm , Where exactly should you specify the destinations in the command? My code - ./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=</Users/gooseexet/Downloads/Ipod_2g_emulator>,nand=</Users/gooseexet/Downloads/Ipod_2g_emulator>,nor=</Users/gooseexet/Downloads/Ipod_2g_emulator> -serial mon:stdio -cpu max -m 2G -d unimp

**Comment by angryduck1** [comment]
> вы не указали местонахождение файлов в вашей команде
> 
> `./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=<paste_boot_rom_location_here>,nand=<paste_nand_location_here>,nor=<paste_nor_location_here> -serial mon:stdio -cpu max -m 2G -d unimp`
> 
> вам также необходимо извлечь NAND

Can you please tell me where in that command I need to change something and what to change it to?

**Comment by MrDiagnose** [comment]
https://github.com/devos50/qemu-ios/releases/tag/n72ap_v1Hello

after downloading these copy them all to one location like say ipod_files extract the nand file there and also copy the `qemu-system-arm` executable from the build directory there & then use this command -

`./qemu-system-arm -M iPod-Touch,bootrom=bootrom_240_4,nand=nand,nor=nor_n72ap.bin -serial mon:stdio -cpu max -m 2G -d unimp
`

https://github.com/devos50/qemu-ios/issues/128#issuecomment-1899008568
![297845757-d351eac1-daf8-4a66-85f6-799d49a25789](https://github.com/devos50/qemu-ios/assets/23004075/b1d0113d-fa8d-4b3f-8804-36fa8ff2a279)


https://www.youtube.com/watch?v=bxg4QlwENsI

**Comment by angryduck1** [comment]
> https://github.com/devos50/qemu-ios/releases/tag/n72ap_v1Hello
> 
> after downloading these copy them all to one location like say ipod_files extract the nand file there and also copy the `qemu-system-arm` executable from the build directory there & then use this command -
> 
> `./qemu-system-arm -M iPod-Touch,bootrom=bootrom_240_4,nand=nand,nor=nor_n72ap.bin -serial mon:stdio -cpu max -m 2G -d unimp `
> 
> [#128 (comment)](https://github.com/devos50/qemu-ios/issues/128#issuecomment-1899008568) ![297845757-d351eac1-daf8-4a66-85f6-799d49a25789](https://private-user-images.githubusercontent.com/23004075/300279565-b1d0113d-fa8d-4b3f-8804-36fa8ff2a279.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjE0MzMsIm5iZiI6MTcwNjQ2MTEzMywicGF0aCI6Ii8yMzAwNDA3NS8zMDAyNzk1NjUtYjFkMDExM2QtZmE4ZC00YjNmLTg4MDQtMzZmYThmZjJhMjc5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE2NTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYzE2MTk0MTI1ODNhZjA0NmNmOTdlZDFhOThkOGVlMmY0ZjY2ODAyNDJhYzI4YjVlZDcwNDJlZmMxNjEzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a37d33NMNwwvM0cUi8eeSsDCA-hF_rXRWI_T3SY-TEU)
> 
> https://www.youtube.com/watch?v=bxg4QlwENsI

Property 'iPod-Touch-machine.nor' not found . (I did everything right and then this error)

**Comment by MrDiagnose** [comment]
was your build completed successfully? does this work `./qemu-system-arm --version` ? does it show qemu version?

**Comment by angryduck1** [comment]
> ваша сборка завершилась успешно? Это работает `./qemu-system-arm --version`? он показывает версию qemu?

yes

**Comment by MrDiagnose** [comment]
can your share a screenshot of your folder like I have shared

**Comment by angryduck1** [comment]
> можешь ли ты поделиться снимком экрана своей папки, как я поделился
![Uploading Снимок экрана 2024-01-28 в 20.16.30.png…]()

**Comment by angryduck1** [comment]
> можешь ли ты поделиться снимком экрана своей папки, как я поделился

<img width="1440" alt="Снимок экрана 2024-01-28 в 20 16 30" src="https://github.com/devos50/qemu-ios/assets/98224800/a58a8a6c-46ea-45f0-ad49-d25f1b728929">

**Comment by MrDiagnose** [comment]
idk should have worked maybe @devos50 can help

**Comment by MrDiagnose** [comment]
qemu-system-arm binary for mac is only 17 mb 🤔 do one thing try moving everything to the build directory

**Comment by angryduck1** [comment]
> qemu-system-arm binary for mac is only 17 mb 🤔 do one thing try moving everything to the build directory

What do I need to do?

**Comment by MrDiagnose** [comment]
> > qemu-system-arm binary for mac is only 17 mb 🤔 do one thing try moving everything to the build directory
> 
> What do I need to do?

try moving https://github.com/devos50/qemu-ios/issues/135#issuecomment-1913665595 to the build directory and then run the command

**Comment by angryduck1** [comment]
> > > Бинарный файл qemu-system-arm для Mac занимает всего 17 МБ 🤔 сделайте одну вещь и попробуйте переместить все в каталог сборки
> > 
> > 
> > Что мне нужно делать?
> 
> попробуйте переместить [# 135 (комментарий)](https://github.com/devos50/qemu-ios/issues/135#issuecomment-1913665595) в каталог сборки, а затем выполните команду

ok I'll try

**Comment by MrDiagnose** [comment]
Ok so I tried it out on Mac OS Catalina it worked the `qemu-system-arm` binary was about 28mb yours is 17mb so make sure you cloned ipod2g & not ipog1g

`git clone https://github.com/devos50/qemu-ios.git`


![VirtualBox_Catalina_29_01_2024_19_10_00](https://github.com/devos50/qemu-ios/assets/23004075/d0c58fbc-632e-4aec-bd12-14892b65d300)

**Comment by angryduck1** [comment]
> Хорошо, я попробовал это на Mac OS Catalina, все сработало, `qemu-system-arm`двоичный файл был около 28 МБ, ваш — 17 МБ, поэтому убедитесь, что вы клонировали ipod2g, а не ipog1g.
> 
> `git clone https://github.com/devos50/qemu-ios.git`
> 
> ![VirtualBox_Catalina_29_01_2024_19_10_00](https://private-user-images.githubusercontent.com/23004075/300480809-d0c58fbc-632e-4aec-bd12-14892b65d300.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzYxNTksIm5iZiI6MTcwNjUzNTg1OSwicGF0aCI6Ii8yMzAwNDA3NS8zMDA0ODA4MDktZDBjNThmYmMtNjMyZS00YWVjLWJkMTItMTQ4OTJiNjVkMzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDEzNDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZDA0ZTkwYTg0NDE2MWM2MmY1Y2I5MzU5MzAyMzkxYWVlYWJmODg0ZDlhYmMzYmJhZjc1ZDU2ZTJkNjllNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IGpGyR_Cevear26e85T8Ojbaojg4ioEDYWh14Skh8mc)

I did this and the folders I built are not in the qemu-ios directories

**Comment by angryduck1** [comment]
> Хорошо, я попробовал это на Mac OS Catalina, все сработало, `qemu-system-arm`двойной файл был около 28 МБ, ваш — 17 МБ, поэтому убедитесь, что вы клонировали ipod2g, а не ipog1g.
> 
> `git clone https://github.com/devos50/qemu-ios.git`
> 
> ![VirtualBox_Catalina_29_01_2024_19_10_00](https://private-user-images.githubusercontent.com/23004075/300480809-d0c58fbc-632e-4aec-bd12-14892b65d300.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzYxNTksIm5iZiI6MTcwNjUzNTg1OSwicGF0aCI6Ii8yMzAwNDA3NS8zMDA0ODA4MDktZDBjNThmYmMtNjMyZS00YWVjLWJkMTItMTQ4OTJiNjVkMzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDEzNDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZDA0ZTkwYTg0NDE2MWM2MmY1Y2I5MzU5MzAyMzkxYWVlYWJmODg0ZDlhYmMzYmJhZjc1ZDU2ZTJkNjllNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IGpGyR_Cevear26e85T8Ojbaojg4ioEDYWh14Skh8mc)

why is there no build after execution?

**Comment by MrDiagnose** [comment]
wait I'll post all my steps make sure you followed them

**Comment by angryduck1** [comment]
> подождите, я опубликую все свои действия, убедитесь, что вы их выполнили

Because of this, I can’t get qemu-system-arm from there

**Comment by angryduck1** [comment]
> подождите, я опубликую все свои действия, убедитесь, что вы их выполнили

ok

**Comment by MrDiagnose** [comment]
1. `brew install glib ninja pixman pkg-config sdl2`
 
2. `git clone https://github.com/devos50/qemu-ios.git`
 
3. `cd qemu-ios`
 
4. `./configure --target-list=arm-softmmu --extra-cflags=-I/usr/local/opt/openssl@3/include --extra-ldflags='-L/usr/local/opt/openssl@3/lib -lcrypto'`
 
5. `make -j4`
 
6. Copy `qemu-system-arm` and store it in a different directory with the iPod Touch 2G Emulation Files: `https://github.com/devos50/qemu-ios/releases/tag/n72ap_v1` (extract the nand zip file in that same directory)
 
7. `./qemu-system-arm -M iPod-Touch,bootrom=bootrom_240_4,nand=nand,nor=nor_n72ap.bin -serial mon:stdio -cpu max -m 2G -d unimp`

**Comment by angryduck1** [comment]
> 4\. ./configure --target-list=arm-softmmu --extra-cflags=-I/usr/local/opt/openssl@3/include --extra-ldflags='-L/usr/local/opt/openssl@3/lib -lcrypto'

./configure --target-list=arm-softmmu --extra-cflags=-I/usr/local/opt/openssl@3/include --extra-ldflags='-L/usr/local/opt/openssl@3/lib -lcrypto'       - ./build' as the directory for build output

**Comment by angryduck1** [comment]
where is build

**Comment by MrDiagnose** [comment]
> where is build

it will be created automatically

**Comment by angryduck1** [comment]
> > where is build
> 
> it will be created automatically

Why is build not being created hmm

**Comment by MrDiagnose** [comment]
not needed

**Comment by angryduck1** [comment]
> not needed

Could you please post your build folder and upload it to google drive?

**Comment by angryduck1** [comment]
> * `make -j4`
> *

yeah build is crated

**Comment by angryduck1** [comment]
> 7\. ./qemu-system-arm -M iPod-Touch,bootrom=bootrom_240_4,nand=nand,nor=nor_n72ap.bin -serial mon:stdio -cpu max -m 2G -d unimp

Thank you very much! It started!

**Comment by angryduck1** [comment]
> not needed

I wonder if it's possible to put a jailbreak in there?

**Comment by MrDiagnose** [comment]
> > 7. ./qemu-system-arm -M iPod-Touch,bootrom=bootrom_240_4,nand=nand,nor=nor_n72ap.bin -serial mon:stdio -cpu max -m 2G -d unimp
> 
> Thank you very much! It started!

Happy to help 😊 since the issue was resolved you should close it 👍

**Comment by suoko** [comment]
Trying on Ubuntu 24.04 this way after installing ninja-build, meson, libssl-dev,  libssl3 and  python3-sphinx:
```
/configure --target-list=arm-softmmu --disable-werror
make -j4
```

but got a:
```
FAILED: qemu-system-arm 
cc -m64 -mcx16 @qemu-system-arm.rsp
...
collect2: error: ld returned 1 exit status
...
ninja: build stopped: subcommand failed.
```
