### ISSUE TITLE
Root shell

### ISSUE THREAD

**Issue by ghost** [devos50/qemu#151]
Not really an issue, but how do I get a root shell on the emulator?

**Comment by zoe-vb** [comment]
Hi, if you're interested in a root shell, there's the single mode nor image option for the ipod touch 1st generation version which uses single mode. 
This requires the construction of a modified filesystem image in addition to the modified nor image.

**Comment by ghost** [comment]
Hmmm how can I do that??

**Comment by zoe-vb** [comment]
[https://github.com/devos50/qemu-ios-generate-nand/tree/main/docs](url) please read the changes documentation and then follow the instructions for single user mode. You will need [https://github.com/devos50/qemu-ios-generate-nor/tree/single_user_mode](url) also

**Comment by jeppojeps** [comment]
I have made some good progress

https://github.com/devos50/qemu-ios/issues/140

**Comment by ghost** [comment]
Closed as resolved
