### ISSUE TITLE
Error while building. "Warnings being treated as errors"

### ISSUE THREAD

**Issue by Anthpect101** [devos50/qemu#168]
Greetings,
I have encountered an error while building. 
I don't know if it's my side or not, but I from I am thinking, it treats warnings as errors, which caused it to stop.
I don't have a screenshot but just plain text (sorry) :

`[833/2120] Compiling C object libcommon.fa.p/hw_i2c_omap_i2c.c.o                                     [834/2120] Compiling C object libcommon.fa.p/hw_i2c_i2c_mux_pca954x.c.o                              [835/2120] Compiling C object libcommon.fa.p/hw_i2c_pmbus_device.c.o                                 [836/2120] Compiling C object libcommon.fa.p/hw_i2c_ipod_touch_i2c.c.o                               FAILED: libcommon.fa.p/hw_i2c_ipod_touch_i2c.c.o                                                     cc -Ilibcommon.fa.p -Isubprojects/dtc/libfdt -I../subprojects/dtc/libfdt -I/usr/include/p11-kit-1 -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/SDL2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/gio-unix-2.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/cloudproviders -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/vte-2.91 -I/usr/include/libusb-1.0 -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/openssl -fdiagnostics-color=auto -Wall -Winvalid-pch -Werror -std=gnu11 -O2 -g -fstack-protector-strong -Wundef -Wwrite-strings -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wold-style-declaration -Wold-style-definition -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wimplicit-fallthrough=2 -Wmissing-format-attribute -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-psabi -Wshadow=local -isystem /home/Anthpect101/qemu-ios/linux-headers -isystem linux-headers -iquote . -iquote /home/Anthpect101/qemu-ios -iquote /home/Anthpect101/qemu-ios/include -iquote /home/Anthpect101/qemu-ios/host/include/aarch64 -iquote /home/Anthpect101/qemu-ios/host/include/generic -iquote /home/Anthpect101/qemu-ios/tcg/aarch64 -pthread -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-common -fwrapv -fno-pie -no-pie -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DNCURSES_WIDECHAR=1 -D_REENTRANT -DSTRUCT_IOVEC_DEFINED -MD -MQ libcommon.fa.p/hw_i2c_ipod_touch_i2c.c.o -MF libcommon.fa.p/hw_i2c_ipod_touch_i2c.c.o.d -o libcommon.fa.p/hw_i2c_ipod_touch_i2c.c.o -c ../hw/i2c/ipod_touch_i2c.c                                     ../hw/i2c/ipod_touch_i2c.c: In function ‘s5l8900_i2c_update’:                                        ../hw/i2c/ipod_touch_i2c.c:27:14: error: variable ‘level’ set but not used [-Werror=unused-but-set-variable]                                                                                                 27 |     uint16_t level;                                                                                |              ^~~~~                                                                           cc1: all warnings being treated as errors                                                            ninja: build stopped: subcommand failed.
make: *** [Makefile:162: run-ninja] Error 1
[Anthpect101@localhost build]$`

Thank you for your time :-).

**Comment by ToasterGithubUser** [comment]
try " --disable-werror "

**Comment by ToasterGithubUser** [comment]
try " --disable-werror " in configure options

**Comment by devos50** [comment]
@Anthpect101 thank you for your report. Adding the `--disable-werror` should fix the issue I believe. Can you confirm this?

**Comment by Anthpect101** [comment]
> @Anthpect101 thank you for your report. Adding the `--disable-werror` should fix the issue I believe. Can you confirm this?

Thank you both, it worked.
