### ISSUE TITLE
cant do pull requests

### ISSUE THREAD

**Issue by daniilfigasystems** [devos50/qemu#169]
i cant do pull requests only for this repo i have fixed bugs added new things fixed slow ios and added semi-working wifi

**Comment by devos50** [comment]
Thank you for your report. I don't see why PRs wouldn't work in this repository. Perhaps you have an error or more details about what's going wrong?

**Comment by daniilfigasystems** [comment]
> Thank you for your report. I don't see why PRs wouldn't work in this repository. Perhaps you have an error or more details about what's going wrong?

When I do pull request, i getting unknown error

**Comment by daniilfigasystems** [comment]
I will try to fix it. Maybe it’s my fault.

**Comment by devos50** [comment]
With #170 this seems to be fixed?

**Comment by daniilfigasystems** [comment]
Yes it was GitHub trouble. Sorry I forgot about this issue
