### ISSUE TITLE
Segmenting Fault

### ISSUE THREAD

**Issue by misha99fr** [devos50/qemu#178]

**Comment by daniilfigasystems** [comment]
Can you provide more info? Console output?

**Comment by misha99fr** [comment]
Update to Ubuntu 24 fixed this close plz

пн, 19 авг. 2024 г., 04:10 Daniil ***@***.***>:

**Comment by daniilfigasystems** [comment]
You can close it yourself.

**Comment by gdandsm64fan123** [comment]
hmmmm if this is indeed the case, maybe updating my linux should do it too

**Comment by Opuqide** [comment]
I've had an error like this, I didn't even know how to fix this, other than having to use another version of Ubuntu (well, with ubuntu-desktop) added, but as another version! But, let's hope it's fixed soon!
