### ISSUE TITLE
Unrecognized host OS (uname -s reports 'Linux')

### ISSUE THREAD

**Issue by StereoLuigi99** [devos50/qemu#181]
I'm using Fedora Workstation 40. I don't know why but this error shows up whenever I try to execute the configure script.

CPU: Intel Core i5-7200U
OS: Fedora Workstation 40

![image](https://github.com/user-attachments/assets/a5d5d100-91cb-490f-92b9-74302f7a7395)

**Comment by StereoLuigi99** [comment]
Problem is solved by installing these packages:
`sudo dnf5 install make automake gcc gcc-c++ kernel-devel`

**Comment by gdandsm64fan123** [comment]
this would´ve helped me back in the day man
