### ISSUE TITLE
./qemu-system-arm: No such file or directory

### ISSUE THREAD

**Issue by corped12** [devos50/qemu#183]
When trying to run the iPod touch 2G emulator on my raspberry pi 4b i get this error
./qemu-system-arm: No such file or directory
i tried running from the folder it was the qemu-system-arm file was in and still got the error (currently im running from the folder but normally it would say ./home/corped/qemu-ios/build/arm-softmmu/qemu-system-arm: No such file or directory)
![20240915_13h35m49s_grim](https://github.com/user-attachments/assets/ed0a923d-02b3-4e57-ac2d-32219fcc5f92)

**Comment by corped12** [comment]
forgot to mention the file qemu-system-arm does exist

**Comment by zoe-vb** [comment]
Have you actually compiled the program. qemu-system-arm won't be there until it is successfully compiled.

**Comment by corped12** [comment]
> Have you actually compiled the program. qemu-system-arm won't be there until it is successfully compiled.

it is there but it appears as a broken link file

**Comment by corped12** [comment]
turns out i just forgot to compile it
