### ISSUE TITLE
Having Trouble Compiling On Windows 10

### ISSUE THREAD

**Issue by hyperwilliam** [devos50/qemu#186]
![Capteeure](https://github.com/user-attachments/assets/e2af2505-854f-40ec-a966-a681a7aeb1cf)

**Comment by tr1fled** [comment]
I got the fix for you, do you have discord? It would be easier to explain the patches there, if not LMK so I can help you here.

PS: you're not the only one, i just fixed this like 5 minutes ago.

**Comment by tr1fled** [comment]
You probably don't have discord, so here you go

open these two files in your preferred text editor
```
hw/arm/ipod_touch_nor_spi.c
hw/arm/ipod_touch_2g.c
```
replace all ocurrences for
```
unsigned long fsize;
```
to
```
gsize fsize;
```
after that, it should flawlessly compile.

**Comment by hyperwilliam** [comment]
It Worked! Thanks.
