### ISSUE TITLE
Issues Running qemu-system-arm

### ISSUE THREAD

**Issue by hyperwilliam** [devos50/qemu#188]
It Seems That When I Try Run Any command on qemu-system-arm, it complains about a bunch of missing .dll files.

**Comment by tr1fled** [comment]
Did you compile it yourself? if not, I can help you.

**Comment by hyperwilliam** [comment]
i compiled it myself.

**Comment by hyperwilliam** [comment]
Issue Solved. it seems that i needed to re-install my other regular qemu build. (that one has the .dll files that i needed,)
