### ISSUE TITLE
iPod Touch 2G Emulator Has Problems Booting Up.

### ISSUE THREAD

**Issue by hyperwilliam** [devos50/qemu#190]
![ipod issue](https://github.com/user-attachments/assets/f716d867-6fef-40be-b329-181514fb07bf)
iPod Keeps Looping Between The 2 Text Logs Shown In The Image When Booting Up.

**Comment by tr1fled** [comment]
Which platform?

**Comment by hyperwilliam** [comment]
using windows

**Comment by hyperwilliam** [comment]
windows 10, To Be specific.

**Comment by hyperwilliam** [comment]
FIX Found: Run Another Operating system using Virtualisation software (Not Convenient, But Worked.)

**Comment by hyperwilliam** [comment]
recently i actually did manage to compile this without issues, and it runs great!
