### ISSUE TITLE
unsupported machine type: "iPod-Touch" (Arch)

### ISSUE THREAD

**Issue by huso-lab** [devos50/qemu#194]
i've done everything but im getting this error when i check supported machines there is no ipod touch

**Comment by Opuqide** [comment]
@huso-lab I think you used the normal "qemu-system-arm" command, did you run `make` in the terminal? Because that's what builds the emulator, as seen in the instructions.

**Comment by huso-lab** [comment]
> @huso-lab I think you used the normal "qemu-system-arm" command, did you run `make` in the terminal? Because that's what builds the emulator, as seen in the instructions.

i got it to work thanks
