### ISSUE TITLE
License misattribution in `ipod_touch_spi.c`

### ISSUE THREAD

**Issue by TrungNguyen1909** [devos50/qemu#2]
Hi,
I came across the file `hw/arm/ipod_touch_spi.c` in your repo and found out that after a heavy rework in logic in commit 13ffc18,
its logic is mostly based off my code at [qemu-t8030 repo](https://github.com/TrungNguyen1909/qemu-t8030/blob/master/hw/ssi/apple_spi.c) with some changes for your own purpose.

Meanwhile, the license header in your file still stated: 
```
/*
 * S5L8900 SPI Emulation
 *
 * by cmw
 */
```

which is a misattribution to both you and me.

While I am not bothered with my code being used in another fork since it is GPLv2 anyway, please consider fixing the attribution.

Thank you very much.

**Comment by devos50** [comment]
Thank you for pointing this out! I just fixed the attribution in https://github.com/devos50/qemu/commit/8905df5bac024a7f311169afa09720f7b7b9cdd8 👍
