### ISSUE TITLE
When compiling qemu I get an error

### ISSUE THREAD

**Issue by Lolguy1** [devos50/qemu#200]
I'm on windows 11 pro 24h2
When I try to compile qemu I get this error:

-bash: ./configure: No such file or directory
make: *** No targets specified and no makefile found. Stop.

Does anyone know how to fix it?

**Comment by Lolguy1** [comment]
Also if I need to CD into build can someone show me the directory I need to CD in please?

**Comment by devos50** [comment]
Sorry, this was an error in the `README.md` file, the command should be: `../configure` 👍
