### ISSUE TITLE
How to press the Home Button?

### ISSUE THREAD

**Issue by PFOASafe** [devos50/qemu#206]
I compiled it with no issues and runs great! I just was a little curious about where the home button is. I truly admire what you have done to make this possible.

**Comment by heathercat123** [comment]
Press H on your keyboard

**Comment by PFOASafe** [comment]
Thanks. Merry Christmas!

**Comment by devos50** [comment]
Yes indeed, pressing `h` should bring you to the Home Screen. Merry Christmas to you too! 🎄
