### ISSUE TITLE
iPod Touch 1G black screen no serial on linux

### ISSUE THREAD

**Issue by zoe-vb** [devos50/qemu#21]
When running the recommended command on linux, the qemu emulator will open but the screen will remain black and there is zero output. 
Please could you look into this issue?

**Comment by devos50** [comment]
Hi, it is hard to say what can be wrong without other logs. It seems likely that the emulator fails at a very early stage, even before any `printf` function is being called. Could you let me know if you're sure every instruction you followed is correct?

**Comment by zoe-vb** [comment]
> Hi, it is hard to say what can be wrong without other logs. It seems likely that the emulator fails at a very early stage, even before any `printf` function is being called. Could you let me know if you're sure every instruction you followed is correct?

../configure --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-pie --disable-slirp --extra-ldflags='-lcrypto' --disable-werror

This was what I used to build on linux as some of the flags were for Mac OS using homebrew. 
If --disable-werror isn't added the project won't build due to initialized variables. 
Qemu won't even put anything in a log and I'm using the iPod 1G branch from this repo

**Comment by zoe-vb** [comment]
Solved - an absolute path has to be used you cannot use "~/" or "../"
