### ISSUE TITLE
What changes needed to be made to generate a viable rootfs for emulation on qemu?

### ISSUE THREAD

**Issue by zoe-vb** [devos50/qemu#22]
In your blog you mentioned that you created rootfs-writeable.dmg with modifications for emulation and I was just wondering what those modifications actually were, in order to perhaps create an iOS 3.1.3 rootfs

**Comment by devos50** [comment]
That's a good question! Unfortunately, I haven't documented all the changes that I made (somewhat stupid on my side, I should have kept track of these changes), and just modified particular files on the go. From what I can remember:
- I modified the fstab file to just have one partition and made it writable.
- I copied the activation records from a real device to the dmg file I used for the emulation.
- I added the kernelcache file to the proper location so it can be loaded by iBoot.

I'm currently trying to get a iPod Touch 2G up and running, and the moment I start working on the NAND image, I will meticulously keep track of these changes! 😁

**Comment by zoe-vb** [comment]
I'll have a look around and see if I can figure out exactly what was done

**Comment by iarchiveml** [comment]
What path did you add the kernelcache to? I diffchecked the stock filesystem and your filesystem and I couldn't find anything related to kernelcache.

**Comment by devos50** [comment]
IIRC, the kernelcache can be found in the directory `/System/Library/Caches/com.apple.kernelcaches`. I believe this file is not included in the stock filesystem as it is put in a separate file partition during the restoration process.

**Comment by iarchiveml** [comment]
It is included in the stock filesystem.

**Comment by devos50** [comment]
Ah then I misremembered! 👍

**Comment by iarchiveml** [comment]
I'm getting "failed to mount root filesystem" errors from iBoot and I have no idea why.
