### ISSUE TITLE
qemu-system-arm: ,iboot=: drive with bus=0, unit=0 (index=0) exists

### ISSUE THREAD

**Issue by fruitbow1** [devos50/qemu#3]
MacBook Pro 2017 
Monterey 12.1 

Upon executing the command (./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom= /Users/callumchandler/Documents/iPod/bootrom_s5l8900 ,iboot= /Users/callumchandler/Documents/iPod/iboot_204_n45ap.bin  ,nand= /Users/callumchandler/Documents/iPod/nand -serial mon:stdio -cpu max -m 1G -d unimp -pflash /Users/callumchandler/Documents/iPod/nor_n45ap.bin) I get;

WARNING: Image format was not specified for '/Users/callumchandler/Documents/iPod/bootrom_s5l8900' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
qemu-system-arm: ,iboot=: drive with bus=0, unit=0 (index=0) exists

Any Ideas?

**Comment by breakgimme** [comment]
from what i've tested, you seem to have too many spaces in your command
it should be something like
`./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=/Users/callumchandler/Documents/iPod/bootrom_s5l8900,iboot=/Users/callumchandler/Documents/iPod/iboot_204_n45ap.bin,nand=/Users/callumchandler/Documents/iPod/nand -serial mon:stdio -cpu max -m 1G -d unimp -pflash /Users/callumchandler/Documents/iPod/nor_n45ap.bin`

**Comment by fruitbow1** [comment]
You my Sir are a genius XD, I spent about 2hrs trying all manor of commands. Thank you! 

> from what i've tested, you seem to have too many spaces in your command
> it should be something like
> `./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=/Users/callumchandler/Documents/iPod/bootrom_s5l8900,iboot=/Users/callumchandler/Documents/iPod/iboot_204_n45ap.bin,nand=/Users/callumchandler/Documents/iPod/nand -serial mon:stdio -cpu max -m 1G -d unimp -pflash /Users/callumchandler/Documents/iPod/nor_n45ap.bin`

You my Sir are a genius XD, I spent about 2hrs trying all manor of commands. Thank you!

**Comment by devos50** [comment]
@breakgimme thanks for you comment! Since this issue seems to be fixed, I'm closing it 👍 . Please let me know if there are other questions.
