### ISSUE TITLE
Give a proper name

### ISSUE THREAD

**Issue by upintheairsheep** [devos50/qemu#35]
Can we give a proper name to this emulator, like QEMU-T9080 is called TruEmu and QEMU-sxxxx5 is called iEmu. We can’t keep going around saying “Devos50’s QEMU fork” all day.

**Comment by devos50** [comment]
Yes, that's definitely a good idea! Any suggestion for a name? Maybe `qemu-iphoneos`?

**Comment by upintheairsheep** [comment]
More name ideas:
qemu-ios 
qemu-ipod
touchLLE
qemu-legacyios 
qemu-iphone 
qemu-apple

**Comment by devos50** [comment]
Thank you! I decided to go for `qemu-ios` as that's the most appropriate and simple repo name for now 👍
