### ISSUE TITLE
qemu terminates with "Property 'iPod-Touch-machine.nand' not found"

### ISSUE THREAD

**Issue by michaelengel** [devos50/qemu#4]
When starting qemu built from the ipod_touch_1g branch, qemu stops with the following error message:
`qemu-system-arm: Property 'iPod-Touch-machine.nand' not found`

I'm starting qemu from the build directory of qemu as follows (all files are present, the NAND image is unzipped):

`./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=/Users/me/Projects/iPhone/qemu/files/bootrom_s5l8900,iboot=/Users/me/Projects/iPhone/qemu/files/iboot_204_n45ap.bin,nand=/Users/me/Projects/iPhone/qemu/files/nand -serial mon:stdio -cpu max -m 1G -d unimp -pflash /Users/me/Projects/iPhone/qemu/files/nor_n45ap.bin`

Running on an M1 Macbook Pro and macOS 12.6.1

I assume that something went wrong with the configuration? Please note that I'm using macports, not homebrew - but I don't think this should make a difference?

`# Configured with: '../configure' '--enable-sdl' '--disable-cocoa' '--target-list=arm-softmmu' '--disable-capstone' '--disable-pie' '--disable-slirp' '--extra-cflags=-I/opt/local/include/openssl-3/' '--extra-ldflags=-L/opt/local/lib/openssl-3/ -lcrypto'`

**Comment by michaelengel** [comment]
Oops, I used the sources I checked out two days ago. git pull and rebuilding solved the issue...

**Comment by devos50** [comment]
Closing this issue since it seems to be resolved 👍
