### ISSUE TITLE
How's the iPod 2g port coming along?

### ISSUE THREAD

**Issue by zoe-vb** [devos50/qemu#51]
I've seen that you've been making commits to the 2G branch and was just wondering how positive you are about it?

**Comment by devos50** [comment]
Yes, I'm currently working on the iPod Touch 2G, indeed! I managed to get all drivers up and running, but it's failing when trying to load the `launchd` executable, which I'm looking into now. The main problem there is the NAND flash layout which also was quite a challenge in the iPod Touch 1G. This time, Apple seems to use the VSVFL protocol, which is more complicated than "plain" VFL, which is used in the previous iteration of the iPod Touch. I'm currently trying to understand the mapping from logical to physical pages, and once I get that up and running, the kernel should be able to run smoothly.

Another thing that's left is the LCD, which uses a slightly different protocol. I have to do some more reverse engineering, but I don't expect that to be very difficult 👍 . The multitouch driver seems to be the same as in the iPod Touch 1G so I probably don't need to spend additional time on that.

All in all, I expect to have a prototype soon! If things work out as I want, I hope to keep iterating on this version and get other components up and running (USB, networking etc).

**Comment by upintheairsheep** [comment]
I’m excited to try out some apps on it! touchHLE’s last commit was 3 weeks
ago. Basically dead. Before that it got per day work.

**Comment by zoe-vb** [comment]
That’s great news, your dedication to this is incredibly impressive as most promising ports get archived or abandoned too soon
