### ISSUE TITLE
iBoot patches

### ISSUE THREAD

**Issue by zoe-vb** [devos50/qemu#52]
In my attempts to fully document patches I was wondering how you changed iBoot? 
I decrypted iBoot directly from the ipsw but it did nothing on qemu, I was wondering if you had patched it at all?

**Comment by devos50** [comment]
I don't remember patching iBoot. Did I mention this somewhere?

**Comment by zoe-vb** [comment]
No, but when trying to load a decrypted iBoot from the ipsw it fails to load on qemu, what tool did you use to decrypt it?
