### ISSUE TITLE
support for img3

### ISSUE THREAD

**Issue by stagbar** [devos50/qemu#56]
In iOS 2.0 version, Apple referenced img3 and replaced img2.
So,when will it be support.

**Comment by devos50** [comment]
I have IMG3 images already working on the iPod Touch 2G branch 👍

**Comment by stagbar** [comment]
so,how can i use iPod Touch 2G branch?

**Comment by devos50** [comment]
Well, the iPod Touch 2G emulator still heavily under development and currently doesn't boot up SpringBoard as I'm still trying to bypass the activation check by `lockdownd`. That said, it does successfully get through the bootrom, LLB, iBoot and starts the most important iOS drivers. Getting it up and running requires some files that I can share with you if you're interested in helping out 👍

**Comment by stagbar** [comment]
I think this things can help you
https://github.com/kennytm/iphone-private-frameworks/commit/cd4c0fb14385c13460171c0eada10dbb5d2dcbe7
https://iphonedevwiki.net/index.php/Liblockdown.dylib

**Comment by DanielVolt** [comment]
hi, i can help out bypassing checks in lockdownd. Could i perhaps have the IMG3 files so i can take a look?
