### ISSUE TITLE
GLib version too old: we're now on 2.76... Source requires: 2.56

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [devos50/qemu#57]
Can't even compile this now... Why don't you provide the emulator binaries at this point?

**Comment by zoe-vb** [comment]
It's still compilable- my Mac on Sonoma with the latest GCC from homebrew and also command line tools from xcode can do it. You should include your platform and toolchain info with issues like this so they can be resolved correctly.

**Comment by RetroSoftwareRepository** [comment]
I’m trying to compile it on Windows to be more specific. Using MSYS2 MINGW64. Windows 11 Pro

Sent from my iPad

On Sep 4, 2023, at 5:26 PM, zoe-vb ***@***.***> wrote:

﻿

It's still compilable- my Mac on Sonoma with the latest GCC from homebrew and also command line tools from xcode can do it. You should include your platform and toolchain info with issues like this so they can be resolved correctly.

**Comment by zoe-vb** [comment]
I don't believe that we're actually testing that platform at the moment. Right now this mainly works on Mac OS (primarily) and Linux. I can look into this.

**Comment by zoe-vb** [comment]
Yep, I've managed to compile the program on windows 11 Pro with msys2 and mingw64. Please follow the instructions on the qemu site for compiling with msys for 64 bits up until the git clone procedure, from there compile this repo instead with the flags --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-slirp --disable-pie --extra-ldflags="-lcrypto" --extra-cflags="-Wno-error"

**Comment by RetroSoftwareRepository** [comment]
I just decided to break down and compile it on WSL2 (Ubuntu 22.04 LTS)

So far so good. Will let you guys know if I hit any roadblocks.

**Comment by devos50** [comment]
I just rebased the `ipod_touch_2g` branch on the latest stable QEMU version so I hope this will fix some incompatibility/library version issues!
