### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zqpvr** [devos50/qemu#58]
how is your work on ipod touch 2g going?

**Comment by devos50** [comment]
At the moment, I managed to bypass the device activation and I'm working on getting Springboard (the GUI) fully functional. It seems that the display server (responsible for rendering the GUI) boots, but I'm running into some issues when Springboard communicates with `configd`. For some reason, the stores created by `SystemConfiguration.framework` are being closed and I haven't figured out the exact reason yet. This blocks SpringBoard from booting. It actually gets very, very far in the booting process so I think once I fix that, and I get the LCD + multitouch working, I might see the home screen! 🎉

**Comment by zqpvr** [comment]
alright good luck and keep going at it!
