### ISSUE TITLE
How to decrypt iBoot?

### ISSUE THREAD

**Issue by coreycusick** [devos50/qemu#59]
How did you get a .bin file? No .img2 or .img3 files work for me at all. They are decrypted but do nothing,

**Comment by devos50** [comment]
Isn't the iBoot IMG2 file in Mach-o format after decryption? Directly loading that in memory and executing it indeed is not supposed to work. I think with some hacks, I managed to load the Mach-o sections into their respective memory locations, and then used GDB to create a dump 👍

**Comment by coreycusick** [comment]
It can be assumed that I'd need a physical device then? or am I misunderstanding?

**Comment by devos50** [comment]
I didn't do this with a device but all in the emulator. For the IT2G, I have the entire boot chain up and running, so I didn't have to map the iBoot Mach-o sections in memory as this was done by LLB. So for the IT2G I just had to put the encrypted iBoot IMG3 file on the NOR flash, and it would automatically be decrypted + loaded by LLB. Hope this clarifies it!
