### ISSUE TITLE
IMG3 support

### ISSUE THREAD

**Issue by DanielVolt** [devos50/qemu#60]
Hey, fellow dutchman here.

Saw you have IPT2G already working and have an issue with lockdownd's activation method. 

I could perhaps help bypassing them, as i think the best method would be writing a dylib that hooks into the lockdownd and hijack the method. Could i get access to the IMG3 stuff, perhaps nand/nor files so i can help out?

Alvast bedankt

**Comment by devos50** [comment]
Hi! Sure, I can send you the relevant files after I'm back from vacation (upcoming Monday). Please send me an email so I have your email address and I will have a look at it once I'm back 👍

**Comment by DanielVolt** [comment]
Gladly sent you an email, cheers en nog een fijne vakantie!
