### ISSUE TITLE
Instructions for the 2G?

### ISSUE THREAD

**Issue by ririinsta** [devos50/qemu#66]
Hello. I was wondering if the instructions for getting at least a experimental build of the 2G are the same as the 1G?

**Comment by devos50** [comment]
Hi! Yes, these instructions are mostly similar in the sense that the IT2G also requires a NOR image, iBoot, bootrom, NAND image etc. I think there are some hard-coded file paths in the code that I should get rid of before making the instructions public.

I'll try to have a go at this sometime this week!

**Comment by ririinsta** [comment]
I see. Thank you! I will keep watch for the instructions. Your project is very interesting.
