### ISSUE TITLE
Unable to build on Apple Silicon Macbook

### ISSUE THREAD

**Issue by tifasoftware** [devos50/qemu#69]
I attempted to build this according to the instructions, however it fails on this:

ld: warning: -undefined error is deprecated
ld: warning: ignoring duplicate libraries: '-lc++', '-lglib-2.0', '-lgmodule-2.0', '-lintl', '-lz'
ld: Undefined symbols:
  _AES_cbc_encrypt, referenced from:
      _ipod_touch_aes_write in hw_arm_ipod_touch_aes.c.o
  _AES_set_decrypt_key, referenced from:
      _ipod_touch_aes_write in hw_arm_ipod_touch_aes.c.o
  _BN_CTX_new, referenced from:
      _ipod_touch_pke_write in hw_arm_ipod_touch_pke.c.o
  _BN_bn2hex, referenced from:
      _ipod_touch_pke_write in hw_arm_ipod_touch_pke.c.o
  _BN_dec2bn, referenced from:
      _ipod_touch_pke_write in hw_arm_ipod_touch_pke.c.o
  _BN_lebin2bn, referenced from:
      _ipod_touch_pke_write in hw_arm_ipod_touch_pke.c.o
      _ipod_touch_pke_write in hw_arm_ipod_touch_pke.c.o
  _BN_mod_exp, referenced from:
      _ipod_touch_pke_write in hw_arm_ipod_touch_pke.c.o
  _BN_new, referenced from:
      _ipod_touch_pke_write in hw_arm_ipod_touch_pke.c.o
      _ipod_touch_pke_write in hw_arm_ipod_touch_pke.c.o
  _SHA1_Final, referenced from:
      _ipod_touch_sha1_read in hw_arm_ipod_touch_sha1.c.o
  _SHA1_Init, referenced from:
      _ipod_touch_sha1_read in hw_arm_ipod_touch_sha1.c.o
  _SHA1_Update, referenced from:
      _ipod_touch_sha1_read in hw_arm_ipod_touch_sha1.c.o

**Comment by devos50** [comment]
@tifasoftware It looks like the compiler is unable to resolve the OpenSSL symbols. Are you sure that the path to the OpenSSL library directory is correct when running `configure`?

**Comment by tifasoftware** [comment]
I was unable to find any mention of the openssl directory when configuring, even with using grep

**Comment by tifasoftware** [comment]
I see no mention of any libssl that is in /opt/homebrew/lib

**Comment by tifasoftware** [comment]
> @tifasoftware It looks like the compiler is unable to resolve the OpenSSL symbols. Are you sure that the path to the OpenSSL library directory is correct when running `configure`?

After poking around for a bit, I still do not know how to verify this

**Comment by tifasoftware** [comment]
The issue is fixed by adding clarification in RUNNING.md
