### ISSUE TITLE
qemu-system-arm application launches but stops responding immediately

### ISSUE THREAD

**Issue by alfiecg24** [devos50/qemu#7]
Hi, I followed the blog post which enabled me to get the emulator up and running. I see serial output in Terminal but don't see a GUI and the `qemu-system-arm` app stops responding as soon as it launches. Is there any reason this may be happening, or is GUI not implemented yet?

**Comment by alfiecg24** [comment]
I thought it may have been due to the fact that I added verbose boot to the boot arguments, but after generating a new NOR without it, I get a lot of messages in serial output saying `unexpected CLCD interrupt: 000000ff` and the issue persists

**Comment by FrederickGeek8** [comment]
I am facing the same issue. I get serial output with `unexpected CLCD interrupt: 000000ff` but the GUI never seems to launch. From the serial output it seems to sleep soon after launching though. I wonder why I'm not seeing anything.

```
config(c0be83bc): starting on IOAccessoryManager, 10
config(c0be83bc): terminating
Unrecognized ADM command: 1024
AppleS5L8900XUSBWrangler::setPowerState state = 0

virtual IOReturn AppleISL29003::setPowerState(long unsigned int, IOService*) powerstate = 0
+ AppleMPVDDriver[0xc0a4ae00]::setPowerStateGated()

MPVD Sleep: DDM CLC is 0x00000000: AppleMBXDevice(0xc0aa9c00)::setPowerState(0)
IOReturn AppleS5L8900XSDIO::setPowerStateGated(long unsigned int, IOService*) : 0, 0xc09c2a00
AppleMultitouchZ2SPI: disabled power
AppleMBXDevice(0xc0aa9c00)::changePowerStateGated(0)
AppleS5L8900XIpodHAL::message
IOIpodUSBDevice::gated_message cable removed, stopping stack
s5l8900_usb_phys_write: write invalid location 0x00000018
         0 [Time 4] [Message System Sleep
Reading PMU register 19
Reading PMU register 20
Reading PMU register 21
Reading PMU register 22
Reading PMU register 23
vic[0] ena c00c1c9f
vic[1] ena 000405e3
pmu go hib
```

**Comment by FrederickGeek8** [comment]
I was able to solve this by adding the `-display sdl` flag to the `qemu-system-arm` launch command. The errors are still in the terminal, but the GUI appears.

**Comment by alfiecg24** [comment]
Yep, works for me - thanks for your help

**Comment by fwcd** [comment]
> I was able to solve this by adding the `-display sdl` flag to the `qemu-system-arm` launch command.

That fixed it for me too, perhaps this flag should be added to the [launch instructions](https://github.com/devos50/qemu-ios/blob/ipod_touch_2g/RUNNING.md)?
