### ISSUE TITLE
2G emulator does not compile under Linux

### ISSUE THREAD

**Issue by LagLifeYT** [devos50/qemu#71]
The iPod Touch 2G emulator does not compile under Linux at the moment. Using the default build instructions causes an error in the early build process, however this can be fixed by adding -fPIE to the cflags. Another one comes up dealing with some warning, which is being treated as an error. Disabling that with --disable-werror yields this:

../util/memalign.c: In function ‘qemu_try_memalign’:
../util/memalign.c:65:6: error: #error No function to allocate aligned memory available
   65 |     #error No function to allocate aligned memory available
      |      ^~~~~
Configure command: 
../configure --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-pie --disable-slirp --extra-cflags=-fPIE --disable-werror --extra-ldflags='-L -lcrypto'

**Comment by LagLifeYT** [comment]
Got quite a bit further by enabling PIE and then disabling werror, but the resulting binary just segfaults... (it does run through all the compiling though!

**Comment by devos50** [comment]
@LagLifeYT thanks for reporting! Do you perhaps have a trace/crash log/core dump to pinpoint where it goes wrong?

**Comment by lumaaaaaa** [comment]
Confirming, I have the same issue on Arch Linux. @LagLifeYT Using your configure command gets a bit further, but still have not been able to compile. Any chance you can tell me the command you used to get the binary to compile?

**Comment by lumaaaaaa** [comment]
@LagLifeYT

Successful compile and boot on Arch Linux with configure command: `../configure --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-slirp --extra-cflags=-I/usr/include/openssl --extra-ldflags='-L/usr/lib -lcrypto' --enable-pie --disable-werror`

Thanks @devos50 for your work, this is remarkable.
![iOS on Arch](https://github.com/devos50/qemu-ios/assets/24190720/c4ee033a-dd3e-4e02-a9ad-23c56ea7ec4c)

**Comment by LagLifeYT** [comment]
Still not working for me, it just segfaults and core dumps. I can't even find the core dump even though they are enabled and it doesn't even pop up with any window before it dies. Suprisingly the other machines work just fine, I'm going to try a few more configure commands before trying to get a core dump and then posting that here. I'm honestly wondering if Ubuntu 22.04 is too old for this.

**Comment by devos50** [comment]
I probably have to think about better debugging capabilities for this. It could be that the segfault arises when executing the bootrom, boot loader, kernel, or some other binary.

**Comment by LagLifeYT** [comment]
Seems like the emulator only works on recent Linuxes, Ubuntu 23.10 works with it.
![iPodTouch2G](https://github.com/devos50/qemu-ios/assets/147282396/e596f141-a7ba-4a21-9d44-b3e9792a18bf)
@devos50 seems like the issue was solved, @lumaaaaaa's configure command worked

**Comment by nanopone** [comment]
> ../configure --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-slirp --extra-cflags=-I/usr/include/openssl --extra-ldflags='-L/usr/lib -lcrypto' --enable-pie --disable-werror

on fedora workstation 39, i get:
`ERROR: "cc" cannot build an executable (is your linker broken?)`

**Comment by Larry-the-Pig** [comment]
> on fedora workstation 39, i get: `ERROR: "cc" cannot build an executable (is your linker broken?)`

I had a similar error on Debian, I needed to install libssl-dev, the Fedora equivalent is openssl-devel.

**Comment by iAmInActions** [comment]
Small tip that helped me get this working on a brandless mediatek tablet mainboard: use gcc 10 or newer. its also recommended to have the linux headers installed into the global include and not just the user include.
