### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by CrotchBurnt** [devos50/qemu#72]
Starting with 
`./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=~/Downloads/ipodtouch/bootrom_240_4,nand=~/Downloads/ipodtouch/nand,nor=~/Downloads/ipodtouch/nor_n72ap.bin -serial mon:stdio -cpu max -m 2G -d unimp`
error shows:
`[1]    154991 segmentation fault (core dumped)  ./arm-softmmu/qemu-system-arm -M  -serial mon:stdio -cpu max -m 2G -d unimp`

**Comment by jeppojeps** [comment]
see #75
