### ISSUE TITLE
A few issues on compilation Apple silicon vs Ubuntu Intel

### ISSUE THREAD

**Issue by jeppojeps** [devos50/qemu#79]
I immediately figured that somehow the configure script messes with the PIE flag on linux, forcing me enabling it, probably messing other stuff, also it seems warnings are treated as errors, so I will check what I was using for the 1g version and let you know what is going on there too

**Comment by devos50** [comment]
@jeppojeps did you manage to figure this out? If so, could you add the appropriate instructions to [this file](https://github.com/devos50/qemu-ios/blob/ipod_touch_2g/RUNNING.md) perhaps?

Otherwise, I'll try to have a look once I get access to some Ubuntu machine 👍

**Comment by jeppojeps** [comment]
I did fix it but forgot to tell. Until next week I am afk...
