### ISSUE TITLE
Cannot build on Windows, missing pixman-1

### ISSUE THREAD

**Issue by Polytelus** [devos50/qemu#86]
Trying to build the source (with MINGW64, Windows 11 Pro) produces:
`../meson.build:553:2: ERROR: Dependency "pixman-1" not found, tried pkgconfig
`
Pixman is installed.
pkg-config is avaliable.
It can't use pkgconfig.
What should I do?

**Comment by Larry-the-Pig** [comment]
you probably need to install the dev package. what package manager are you using?

**Comment by Polytelus** [comment]
> you probably need to install the dev package. what package manager are you using?

The package manager is **pacman** on **MSYS2 mingw64**. A "dev" package does not exist as pixman comes in form of `mingw-w64-x86_64-pixman`, searching with `pacman -Ss pixman`. Searching for pixman-1 returns nothing.

**Comment by devos50** [comment]
The instructions/commands in [this file](https://github.com/devos50/qemu-ios/blob/ipod_touch_2g/RUNNING.md) should be sufficient to resolve this. If not, please re-open this issue 👍 .
