### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by Kalata2231** [devos50/qemu#89]
Hey can you make a tutorial how to run it
-Kalata

**Comment by spetterman66** [comment]
Hello! What is your operating system?

**Comment by Kalata2231** [comment]
win 10

**Comment by spetterman66** [comment]
Download MSYS2 https://www.msys2.org/wiki/MSYS2-installation/, and open MINGW64. Then use the instructions at https://github.com/devos50/qemu-ios/blob/ipod_touch_2g/RUNNING.md#building-qemu.

**Comment by Kalata2231** [comment]
thanks
